name: 'send-notification-issues'
description: 'Notify issue assignees with a issue comment based on a file'
author: 'tspascoal'
inputs:
  token:
    required: false
    description: auth token
    default: ${{ github.token }}
  number:
    required: true
    description: Issue Number
  
runs:
  using: 'node12'
  main: 'dist/index.js'
