name: FastTrack Requests
description: Request a FastTrack from a GitHub Account
labels: Triage
assignees: tspascoal
title: FastTrack for $CustomerName
body:
- type: markdown
  attributes:
    value: |-
      ## Company and customer information
- type: input
  attributes:
    label: Customer Name
    description: Customer Name
  validations:
    required: true
- type: input
  attributes:
    label: Link to the Account Record in Sales Force
    description: Link to the Account Record in Sales Force
  validations:
    required: true
- type: textarea
  attributes:
    label: "Customer contacts"
    description: "Customer contacts (name, email)"
    render: RENDER WHAT IS THIS?
  validations:
    required: false
- type: input
  attributes:
    label: Customer's executive sponsor
    description: Customer's executive sponsor
  validations:
    required: false
- type: input
  id: TESTID
  attributes:
    label: TEST LABEL
    description: THIS IS A DESCRIPTION
    placeholder: THIS IS A PLACEHOLDER
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: FT Type
    options:
      - Depth
      - Breadth
  validations:
    required: true
 
