trigger: approve
title: Approve FastTrack
description: Removes Fastrack from Triage and passes it to the approval stage

surfaces:
  - issue
  
steps:
  - type: form
    style: modal
    body:
    - type: fill
      template: "The FastTrack has been approved"
#      - type: dropdown
#        attributes:
#          label: Approve
#          description: Yes this fastrack approved?
#          options:
#            - label: 🟢 go
#              value: approve
#            - label: 🔴 no go
#              value: reject
#        validations:
#          required: true

    actions:
      submit: Submit
      cancel: Cancel
    
  - type: repository_dispatch
    eventType: approve
    repository: github/fasttrack-staging
