trigger: schedule
title: Schedule FastTrack
description: Changes status of FT to schedule and optionally set dates

surfaces:
  - issue
  
steps:
  - type: fill
    template: "The FastTrack has been approved"

  - type: form
    style: modal
    body:
      - type: input
        attributes:
          label: Start Date
          description: Start date (if known)
          format: date
        validations:
          required: false
      - type: input
        attributes:
          label: Finish Date
          description: End date
          format: date
        validations:
          required: false
 
    actions:
      submit: Submit
      cancel: Cancel
    
  - type: repository_dispatch
    eventType: schedule
    repository: GuacamoleResearch/ft-staging
