trigger: TEST
title: TEST
surfaces:
  - issue

description: This is an example

steps:
  # This displays a menu, similar to typing `@`.
  - type: menu
    id: some_options
    label: Options
    options:
      - Item 1
      - Item 2
      - Item 3
  # This displays a form with a dropdown, text input, and markdown editor.
  - type: form
    style: modal
    body:
      - type: dropdown
        attributes:
          label: Priority
          options:
          - label: "🟢 Normal"
          - label: "⚠️ Important"
          - label: "💥 Emergency"
      - type: input
        attributes:
          label: Name
          format: text
      - type: textarea
        attributes:
          label: Message
          placeholder: What happened?
  - type: fill
    template: |-
      Thank you for creating a slash command! See
      Here is the data you provided: {{data}}
      And here is some information about the command: {{command}}
