name: Approved/rejected FT
on:
  repository_dispatch:
    types: approve
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$COMMAND_CONTEXT"
      - name: remove triage
        uses: tspascoal/labeler@override-number
        with:
          number: ${{ github.event.client_payload.command.resource.number }}
          add-labels: "triage"
          remove-labels: "approved"
