name: Approved/rejected FT
on:
  repository_dispatch:
    types: approve
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$COMMAND_CONTEXT"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: Fast Track approved by @${{ github.event.client_payload.command.user.login }}
          number: ${{ github.event.client_payload.command.resource.number }}

      - name: remove triage
        uses: tspascoal/labeler@master
        with:
          number: ${{ github.event.client_payload.command.resource.number }}
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          remove-labels: "Triage"
          add-labels: "Approved"
      - name: add tasks to issue (uses template)
        uses: ./actions/append-to-issue
        with:
          number: ${{ github.event.client_payload.command.resource.number }}
          content-path: '.github/templates/fasttrack-tasks.md'

