name: Approved/rejected FT
on:
  repository_dispatch:
    types: approve
permissions:
  issues: write
  contents: read

env:
  issue-number: ${{ github.event.client_payload.command.resource.number }}
  project-number: 4

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$COMMAND_CONTEXT"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: Fast Track approved by @${{ github.event.client_payload.command.user.login }}
          number: ${{ env.issue-number }}

      - name: remove triage and add approved
        uses: andymckay/labeler@1.0.3
        with:
          issue-number: ${{ env.issue-number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          remove-labels: "Triage"
          add-labels: "Approved"

      - name: Add issue ${{ env.issue-number }} to org project
        uses: ./actions/add-issue-to-project
        with:
          project-number: ${{ env.project-number }}
          issue-number: ${{ env.issue-number }}
          token: ${{ secrets.ORG_PAT }}
          set-fields: '{ "Status": "1-Approved" }'

      - name: Assign Issue
        uses: ./actions/assign-issue
        if: github.event.client_payload.data.architects == ''
        with:
          assignees: ${{ github.event.client_payload.data.architects }}
          number: ${{ env.issue-number }}

      - uses: ./actions/send-notification-issues
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues-list: ${{ env.issue-number }}
          content-path: .github/templates/engagement-assigned.md


    


