name: Approved/rejected FT
on:
  repository_dispatch:
    types: approve
permissions:
  issues: write

  contents: read

env:
  issue-number: ${{ github.event.client_payload.command.resource.number }}
  project-number: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$COMMAND_CONTEXT"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: Fast Track approved by @${{ github.event.client_payload.command.user.login }}
          number: ${{ env.issue-number }}

      # TODO update not to use the fork since feature is already there
      - name: remove triage
        uses: tspascoal/labeler@master
        with:
          number: ${{ env.issue-number }}
          # TODO: test with github_token
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          remove-labels: "Triage"
          add-labels: "Approved"

      - name: Add issue ${{ env.issue-number }} to org project
        uses: ./actions/add-issue-to-project
        with:
          project-number: ${{ env.project-number }}
          issue-number: ${{ env.issue-number }}
          token: ${{ secrets.ORG_PAT }}
          set-fields: '{ "Status": "1-Approved" }'
    


