name: Approved/rejected FT
on:
  repository_dispatch:
    types: approve
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$COMMAND_CONTEXT"
      - name: remove triage
        uses: tspascoal/add-remove-label@override-number
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: triage
          type: remove
      - name: add approved
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: triage
          type: remove
