name: Actions CI

on:
  push:
    branches: [main]
    paths: 
      - 'actions/**'
  pull_request:
    branches: [main]
    paths: 
      - 'actions/**'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        
      - name: buld and test append-to-issue
        run: |
          npm ci
          npm run all
        working-directory: actions//append-to-issue

      - name: buld and test get-unclosed-issue-passed-due-date
        run: |
          npm ci
          npm run all
        working-directory: actions/get-unclosed-issue-passed-due-date
        
      - name: buld and test send-notification-issues
        run: |
          npm ci
          npm run all
        working-directory: actions/send-notification-issues

      - name: buld and test /add-issue-to-project
        run: |
          npm ci
          npm run all
        working-directory: actions/add-issue-to-project

  analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript
        queries: +security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1



      
