name: Actions CI

on:
  push:
    branches: [main]
    paths: 
      - 'actions/**'
  pull_request:
    branches: [main]
    paths: 
      - 'actions/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        
      - name: buld and test append-to-issue
        run: |
          npm run ci
          npm run all
        working-directory: actions//append-to-issue

      - name: buld and test get-unclosed-issue-passed-due-date
        run: |
          npm run ci
          npm run all
        working-directory: actions/get-unclosed-issue-passed-due-date
        
      - name: buld and test send-notification-issues
        run: |
          npm run ci
          npm run all
        working-directory: actions/send-notification-issues



      
