name: CurrentFastTrackStatus

on:
  workflow_dispatch:

jobs:
  generate_status_report:
    runs-on: ubuntu-latest
    env:
      FASTRACK_PROJECT_SECRET: ${{ secrets.FASTRACK_PROJECT_SECRET }}
      ORG: GuacamoleResearch
      PROJ: 4
      REPO: ft-staging
      DISC_ID: MDEwOkRpc2N1c3Npb24zNTIzOTQy

    steps:
      - uses: actions/checkout@v2
      - name: Install Prereqs
        run: pip install requests
      - name: Generate summary
        working-directory: .github/workflows
        run: python reporting.py

      
