name: Schedule FT
on:
  repository_dispatch:
    types: schedule

permissions:
  contents: read
  issues: write

env:
  issue-number: ${{ github.event.client_payload.command.resource.number }}
  project-number: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$COMMAND_CONTEXT"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: Fast Track Scheduled by @${{ github.event.client_payload.command.user.login }} TODO ADD DATES
          number: ${{ github.event.client_payload.command.resource.number }}

      - name: add tasks to issue (uses template)
        uses: ./actions/append-to-issue
        with:
          number: ${{ env.issue-number }}
          content-path: '.github/templates/fasttrack-tasks.md'

      - name: Add issue to org project
        uses: ./actions/add-issue-to-project
        with:
          project-number: ${{ env.project-number }}
          issue-number: ${{ env.issue-number }}
          token: ${{ secrets.ORG_PAT }}
          # TODO: fix dates from inputs
          set-fields: '{ "Status": "Approved","Start Date": "2021-01-01" }'
    


